### ISSUE TITLE
Recipe for migration of @LazyCollection annotation

### ISSUE THREAD

**Issue by simonzn** [openrewrite/rewrite-hibernate#16]
## What problem are you trying to solve?

@LazyCollection is deprecated since Hibernate 6.2 and we should use [jakarta.persistence.FetchType](https://javadoc.io/doc/jakarta.persistence/jakarta.persistence-api/3.1.0/jakarta.persistence/jakarta/persistence/FetchType.html) instead.

## Any additional context
[LazyCollectionOption.EXTRA](https://docs.jboss.org/hibernate/orm/6.3/javadocs/org/hibernate/annotations/LazyCollectionOption.html) cannot be directly mapped to FetchType. I don't know if automated migration is feasible in that case.

## Are you interested in contributing this recipe to OpenRewrite
I have implemented a recipe that works well in our project and will open a pull request as a starting point. Please point out all problems and misusages of your API :-)

**Comment by timtebeek** [comment]
Awesome, look forward to your PR. And good seeing you back here! :)
