### ISSUE TITLE
Boolean used to be @Type mappable, but now requires conversion (when migrating from hibernate 5 to 6)

### ISSUE THREAD

**Issue by Laurens-W** [openrewrite/rewrite-hibernate#18]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.14.0
- Maven/Gradle plugin v5.22.0
- rewrite-hibernate v1.1.5

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```
mvn org.openrewrite.maven:rewrite-maven-plugin:5.22.0:run -Drewrite.activeRecipes=redacted -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:5.4.0,org.openrewrite.recipe:rewrite-static-analysis:1.3.0 -Drewrite.exclusions=**api**.yaml
```

## What is the smallest, simplest way to reproduce the problem?

```java
@Entity
class A {
  @Type(type = "boolean")
  private Boolean isAllowed;
}
```

## What did you expect to see?

```java
@Entity
class A {
  @Convert(converter = org.hibernate.type.NumericBooleanConverter.class)
  private Boolean isAllowed;
}
```

## What did you see instead?

```java
@Entity
class A {
  @Type(boolean.class)
  private Boolean isAllowed;
}
```

## What is the full stack trace of any errors you encountered?

It's not necessarily an issue with openrewrite, more that the code left after the recipe ran is non compiling. I think the NumericConverter matches previous behaviour.

**Comment by simonzn** [comment]
I opened #20 for a similar issue - the recipe could easily be extended to fix this (if it is accepted)

**Comment by simonzn** [comment]
I extended #20 so the "boolean" mapping is migrated as well now. We have to somehow ensure that recipe runs before TypeAnnotationParameter, or TypeAnnotationParameter does nothing for `type = "boolean` and `type = "true_false`. Maybe it could check if the type-parameter is a valid FQN?

**Comment by simonzn** [comment]
Added MigrateBooleanMappings to the recipe list, ahead of TypeAnnotationParameter. See #20
